#! /bin/bash

DOCKER_COMMAND=""
if [[ "${1}" == "--docker-mode" ]]; then
    # Docker command for mysqldump
    container="mysql"
    if [[ -n "${2}" ]]; then
        container="${2}"
    fi
    DOCKER_COMMAND="docker exec -i "${container}" /usr/bin/"
fi

# Get current date
now="$(date +'%Y_%m_%d_%H_%M_%S')"

for file in config/.*.db; do
    echo "backing up ${file}"

    # Load Config for the current database backup 
    source $file

    backupDir="${DB_BACKUP_FOLDER}"/"${DB_HOST}"

    # Create the backup folder
    mkdir -p "${backupDir}"

    # Execute the mysql dump
    if eval "${DOCKER_COMMAND}"mysqldump --host "${DB_HOST}" -P "${DB_PORT}" -u "${DB_USER}" -p"${DB_PASSWORD}" -A -R -E --triggers --single-transaction > "${backupDir}"/"${DB_BACKUP_FILE}"_"${now}".sql; then
        echo "backup complete for ${file}"
    fi

    # Delete Old Backups
    # DB_BACKUP_RETENTION = value in days
    find "${backupDir}" -name "*.sql" -type f -mtime +"${DB_BACKUP_RETENTION}" -delete
done
