#! /bin/bash

DOCKER_COMMAND=""
CONFIG_DIRECTORY=.
for i in "$@"; do
    case $1 in
    --docker-mode=*)
        container="${i#*=}"
        if [[ -z "${container}" ]]; then
            container="mysql"
        fi
        DOCKER_COMMAND="docker exec -i ${container} /usr/bin/"
        shift # past argument=value
        ;;
    --config-dir=*)
        CONFIG_DIRECTORY="${i#*=}"
        shift
        ;;
    esac
done

# Get current date
now="$(date +'%Y_%m_%d_%H_%M_%S')"

cd "${CONFIG_DIRECTORY}" || exit 1

for file in .*.db; do
    echo "backing up ${file}"

    # Load Config for the current database backup
    source "${file}"

    backupDir="${DB_BACKUP_FOLDER}"/"${DB_HOST}"

    # Create the backup folder
    mkdir -p "${backupDir}"

    # Execute the mysql dump
    if eval "${DOCKER_COMMAND}"mysqldump --host "${DB_HOST}" -P "${DB_PORT}" -u "${DB_USER}" -p"${DB_PASSWORD}" -A -R -E --triggers --single-transaction >"${backupDir}"/"${DB_BACKUP_FILE}"_"${now}".sql; then
        echo "backup complete for ${file}"
    fi

    # Delete Old Backups
    # DB_BACKUP_RETENTION = value in days
    find "${backupDir}" -name "*.sql" -type f -mtime +"${DB_BACKUP_RETENTION}" -delete
done
