#!/usr/bin/env bash

# Auto Backup
CONFIG_DIRECTORY=.
CONFIG_FILE=

showHelp() {
    echo "Backup - Batch Job DB Backups"
    echo ""
    echo "Usage: backup [<options>...]"
    echo ""
    echo "<options>"
    echo "      --config-file=</path/to/file>   -   Specify the config file, if not specified the script will take the current directory where it is run"
    echo "      --config-dir=</path/to/config>  -   Specify the config directory, if not specified the script will take the current directory where it is run"
    echo "  -h, --help                          -   Shows this help menu"
}

for i in "$@"; do
    case $1 in
    --config-dir=*)
        CONFIG_DIRECTORY="${i#*=}"
        shift
        ;;
    --config-file=*)
        CONFIG_FILE="${i#*=}"
        shift
        ;;
    -h | --help)
        showHelp
        exit 0
        ;;
    esac
done

dateObj="$(date +'%Y_%m_%d')"
timeObj="$(date +'%H_%M_%S')"

function uploadToS3() {
    backupDir="${1}"
    fileName="${2}"
    if [[ "${S3_ENABLED}" == true ]]; then
        if [[ -n "${S3_BUCKET}" ]] && [[ -n "${S3_REGION}" ]]; then
            awsCommand="${AWS_COMMAND_PATH:-aws}"
            if [[ -n "${S3_ACCESS_KEY_ID}" ]] && [[ -n "${S3_SECRET_ACCESS_KEY}" ]]; then
                awsCommand="AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY} ${awsCommand}"
            fi
            if command -v "${awsCommand}" >/dev/null 2>&1; then
                eval "${awsCommand} --profile ${S3_CLI_PROFILE:-default} --region ${S3_REGION} s3 cp ${backupDir}/${fileName} s3://${S3_BUCKET}/${S3_BASE_PATH:-database}/${APP:-$HOST}/${DRIVER}/${fileName}"
            else
                echo "AWS command is not available"
            fi
        else
            echo "S3 bucket is not configured"
        fi
    else
        echo "S3 backup is disabled"
    fi
}

function uploadToCloud() {
    # Cloud Upload goes here
    if ! [[ -f "${1}/${2}" ]]; then
        echo "The file ${1}/${2} does not exist, aborting cloud backup"
    fi
    uploadToS3 "${1}" "${2}"
}

function executeBackup() {
    # set docker command here
    dockerCommand=""
    backedUpFile=""
    if [[ -n "${DOCKER_CONTAINER}" ]]; then
        dockerCommand="docker exec -it ${DOCKER_CONTAINER} "
    fi

    backupCommand=""
    if [[ "${DRIVER}" == "MySQL" ]]; then
        # the mysql dump
        backedUpFile="${BACKUP_FILE}_${timeObj}.sql"
        backupCommand="${dockerCommand}mysqldump --host ${HOST} -P ${PORT} -u ${USER} -p${PASSWORD} -A -R -E --triggers --single-transaction"
    elif [[ "${DRIVER}" == "MongoDB" ]]; then
        # the mongo dump
        backedUpFile="${BACKUP_FILE}_${timeObj}.mongodump"
        backupCommand="${dockerCommand}mongodump --host=${HOST} --port=${PORT} --username=${USER} --password=${PASSWORD} --authenticationDatabase=${AUTHENTICATION_DATABASE} --archive"
    elif [[ "${DRIVER}" == "PostgreSQL" ]]; then
        # the postgres dump
        backedUpFile="${BACKUP_FILE}_${timeObj}.pgsql"
        backupCommand="${dockerCommand}pg_dumpall -c -U ${USER} -h ${HOST} -p ${PORT}"
    else
        echo "Unsupported Database";
    fi

    # execute the backup here ${1} => contains directory of the backup file
    if eval "${backupCommand} >${1}/${backedUpFile}"; then
        uploadToCloud "${1}" "${backedUpFile}"
        echo "backup complete for ${2}"
    else
        echo "backup failed for ${2}"
    fi
}

function deleteOldBackup() {
    # BACKUP_RETENTION = value in days
    find "${1}" \( -name "*.sql" -or -name "*.mongodump" -or -name "*.pgsql" \) -type f -mtime +"${BACKUP_RETENTION}" -delete

    # for aws it is better to configure retention policy through AWS Console
}

function backupFromConfigFile() {
    echo "backing up ${1}"

    # Load Config for the current database mongodb-backup
    source "${1}"

    backupDir="${BACKUP_FOLDER}/${APP:-$HOST}/${DRIVER}/${dateObj}"

    # Create the mongodb-backup folder
    mkdir -p "${backupDir}"

    eval executeBackup "${backupDir}" "${1}"
}

if [[ -n "${CONFIG_FILE}" ]] && [[ -f "${CONFIG_FILE}" ]]; then
    echo "A configuration file has been provided ${CONFIG_FILE}"
    backupFromConfigFile "${CONFIG_FILE}"
elif [[ -n "${CONFIG_DIRECTORY}" ]] && [[ -d "${CONFIG_DIRECTORY}" ]]; then
    echo "A configuration directory has been provided ${CONFIG_DIRECTORY}"
    cd "${CONFIG_DIRECTORY}" || exit 1
    for file in *.db; do
        backupFromConfigFile "${file}"
    done
else
    echo "Invalid configuration"
    exit 1
fi
exit 0
